services:
  liste-de-course:
    image: ghcr.io/soulsstealer48/liste-de-course:latest
    container_name: liste-de-course
    restart: unless-stopped
    ports:
      - "3030:3030"
    volumes:
      - liste-data:/data
    environment:
      - PORT=3030
      - DATA_DIR=/data

volumes:
  liste-data:
